### ISSUE TITLE
Remove WETH pools from testnets

### ISSUE THREAD

**Issue by just-a-node** [connext/monorepo#3931]
## Problem

We should disable WETH pools on all testnets (TEST pools will be set up instead).

## Impact

WETH now has value and pools will keep getting drained.

**Comment by pjenviri** [comment]
Removed WETH pools on testnet.

**Comment by just-a-node** [comment]
Please also remove the My Positions for WETH/ETH pools + remove bridge option for WETH/ETH

**Comment by pjenviri** [comment]
> Please also remove the My Positions for WETH/ETH pools + remove bridge option for WETH/ETH


done.

**Comment by alexwhte** [comment]
@just-a-node please help QA

**Comment by just-a-node** [comment]
Still seeing the options on testnet bridge UI

![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/86388486-37c8-476d-813e-dbb171a71ca4)
![image.png](https://images.zenhubusercontent.com/63331d421176573c6a908c0e/1cf46d07-76d7-42d4-8f5b-9d6c1df68e6e)

**Comment by pjenviri** [comment]
@just-a-node , @rahul told us to bring them back. https://discord.com/channels/992549151134982234/994389387834032198/1093869529517523024

**Comment by just-a-node** [comment]
Ready to remove the pools for real now!

**Comment by alexwhte** [comment]
@just-a-node Can you QA?
